"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdnclient
from sdnclient.model.metadata_query_return_you_search_for_translation_inner_query_field2 import MetadataQueryReturnYouSearchForTranslationInnerQueryField2


class TestMetadataQueryReturnYouSearchForTranslationInnerQueryField2(unittest.TestCase):
    """MetadataQueryReturnYouSearchForTranslationInnerQueryField2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataQueryReturnYouSearchForTranslationInnerQueryField2(self):
        """Test MetadataQueryReturnYouSearchForTranslationInnerQueryField2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetadataQueryReturnYouSearchForTranslationInnerQueryField2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
