"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdn-client
from sdn-client.model.errors_return import ErrorsReturn


class TestErrorsReturn(unittest.TestCase):
    """ErrorsReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorsReturn(self):
        """Test ErrorsReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorsReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
