"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cdi_sdn_py
from cdi_sdn_py.model.order_details_return_download_data_unrestricted import OrderDetailsReturnDownloadDataUnrestricted
globals()['OrderDetailsReturnDownloadDataUnrestricted'] = OrderDetailsReturnDownloadDataUnrestricted
from cdi_sdn_py.model.order_details_return_download_data import OrderDetailsReturnDownloadData


class TestOrderDetailsReturnDownloadData(unittest.TestCase):
    """OrderDetailsReturnDownloadData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderDetailsReturnDownloadData(self):
        """Test OrderDetailsReturnDownloadData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderDetailsReturnDownloadData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
