"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdnclient
from sdnclient.model.order_query_return_warnings import OrderQueryReturnWarnings
globals()['OrderQueryReturnWarnings'] = OrderQueryReturnWarnings
from sdnclient.model.order_query_return import OrderQueryReturn


class TestOrderQueryReturn(unittest.TestCase):
    """OrderQueryReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderQueryReturn(self):
        """Test OrderQueryReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderQueryReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
