"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdnclient
from sdnclient.model.metadata_query_return_facet_search_inner_facet_field1 import MetadataQueryReturnFacetSearchInnerFacetField1
globals()['MetadataQueryReturnFacetSearchInnerFacetField1'] = MetadataQueryReturnFacetSearchInnerFacetField1
from sdnclient.model.metadata_query_return_facet_search_inner import MetadataQueryReturnFacetSearchInner


class TestMetadataQueryReturnFacetSearchInner(unittest.TestCase):
    """MetadataQueryReturnFacetSearchInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataQueryReturnFacetSearchInner(self):
        """Test MetadataQueryReturnFacetSearchInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetadataQueryReturnFacetSearchInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
