"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cdi_sdn_py
from cdi_sdn_py.model.order_list_return_orders_inner import OrderListReturnOrdersInner
globals()['OrderListReturnOrdersInner'] = OrderListReturnOrdersInner
from cdi_sdn_py.model.order_list_return import OrderListReturn


class TestOrderListReturn(unittest.TestCase):
    """OrderListReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderListReturn(self):
        """Test OrderListReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderListReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
