"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdn-client
from sdn-client.model.metadata_query_return_facet_search_inner_facet_field1_steps_inner import MetadataQueryReturnFacetSearchInnerFacetField1StepsInner


class TestMetadataQueryReturnFacetSearchInnerFacetField1StepsInner(unittest.TestCase):
    """MetadataQueryReturnFacetSearchInnerFacetField1StepsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataQueryReturnFacetSearchInnerFacetField1StepsInner(self):
        """Test MetadataQueryReturnFacetSearchInnerFacetField1StepsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetadataQueryReturnFacetSearchInnerFacetField1StepsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
