"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdnclient
from sdnclient.model.order_details_return_download_csv import OrderDetailsReturnDownloadCsv
from sdnclient.model.order_details_return_download_data import OrderDetailsReturnDownloadData
globals()['OrderDetailsReturnDownloadCsv'] = OrderDetailsReturnDownloadCsv
globals()['OrderDetailsReturnDownloadData'] = OrderDetailsReturnDownloadData
from sdnclient.model.order_details_return_download import OrderDetailsReturnDownload


class TestOrderDetailsReturnDownload(unittest.TestCase):
    """OrderDetailsReturnDownload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderDetailsReturnDownload(self):
        """Test OrderDetailsReturnDownload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderDetailsReturnDownload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
