"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import unittest

import sdnclient
from sdnclient.api.metadata_api import MetadataApi  # noqa: E501


class TestMetadataApi(unittest.TestCase):
    """MetadataApi unit test stubs"""

    def setUp(self):
        self.api = MetadataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_metadata_query_post(self):
        """Test case for metadata_query_post

        Make a query and get the metadata back  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
