"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdnclient
from sdnclient.model.order_query_return_warnings import OrderQueryReturnWarnings


class TestOrderQueryReturnWarnings(unittest.TestCase):
    """OrderQueryReturnWarnings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderQueryReturnWarnings(self):
        """Test OrderQueryReturnWarnings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderQueryReturnWarnings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
