"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdn-client
from sdn-client.model.order_list_return_orders_inner_order_number import OrderListReturnOrdersInnerOrderNumber
globals()['OrderListReturnOrdersInnerOrderNumber'] = OrderListReturnOrdersInnerOrderNumber
from sdn-client.model.order_list_return_orders_inner import OrderListReturnOrdersInner


class TestOrderListReturnOrdersInner(unittest.TestCase):
    """OrderListReturnOrdersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderListReturnOrdersInner(self):
        """Test OrderListReturnOrdersInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderListReturnOrdersInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
