"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdn-client
from sdn-client.model.metadata_query_return_you_search_for_translation_inner_query_field1 import MetadataQueryReturnYouSearchForTranslationInnerQueryField1
from sdn-client.model.metadata_query_return_you_search_for_translation_inner_query_field2 import MetadataQueryReturnYouSearchForTranslationInnerQueryField2
globals()['MetadataQueryReturnYouSearchForTranslationInnerQueryField1'] = MetadataQueryReturnYouSearchForTranslationInnerQueryField1
globals()['MetadataQueryReturnYouSearchForTranslationInnerQueryField2'] = MetadataQueryReturnYouSearchForTranslationInnerQueryField2
from sdn-client.model.metadata_query_return_you_search_for_translation_inner import MetadataQueryReturnYouSearchForTranslationInner


class TestMetadataQueryReturnYouSearchForTranslationInner(unittest.TestCase):
    """MetadataQueryReturnYouSearchForTranslationInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataQueryReturnYouSearchForTranslationInner(self):
        """Test MetadataQueryReturnYouSearchForTranslationInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetadataQueryReturnYouSearchForTranslationInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
