"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdn-client
from sdn-client.model.facet_field1 import FacetField1
from sdn-client.model.metadata_query_return_facet_search_inner_facet_field1_steps_inner import MetadataQueryReturnFacetSearchInnerFacetField1StepsInner
globals()['FacetField1'] = FacetField1
globals()['MetadataQueryReturnFacetSearchInnerFacetField1StepsInner'] = MetadataQueryReturnFacetSearchInnerFacetField1StepsInner
from sdn-client.model.metadata_query_return_facet_search_inner_facet_field1 import MetadataQueryReturnFacetSearchInnerFacetField1


class TestMetadataQueryReturnFacetSearchInnerFacetField1(unittest.TestCase):
    """MetadataQueryReturnFacetSearchInnerFacetField1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataQueryReturnFacetSearchInnerFacetField1(self):
        """Test MetadataQueryReturnFacetSearchInnerFacetField1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetadataQueryReturnFacetSearchInnerFacetField1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
