"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdn-client
from sdn-client.model.order_details_return_download import OrderDetailsReturnDownload
globals()['OrderDetailsReturnDownload'] = OrderDetailsReturnDownload
from sdn-client.model.order_details_return import OrderDetailsReturn


class TestOrderDetailsReturn(unittest.TestCase):
    """OrderDetailsReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderDetailsReturn(self):
        """Test OrderDetailsReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderDetailsReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
