"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdnclient
from sdnclient.model.metadata_query_return_facet_search_inner import MetadataQueryReturnFacetSearchInner
from sdnclient.model.metadata_query_return_result_inner import MetadataQueryReturnResultInner
from sdnclient.model.metadata_query_return_you_search_for_translation_inner import MetadataQueryReturnYouSearchForTranslationInner
from sdnclient.model.order_query_return_warnings import OrderQueryReturnWarnings
globals()['MetadataQueryReturnFacetSearchInner'] = MetadataQueryReturnFacetSearchInner
globals()['MetadataQueryReturnResultInner'] = MetadataQueryReturnResultInner
globals()['MetadataQueryReturnYouSearchForTranslationInner'] = MetadataQueryReturnYouSearchForTranslationInner
globals()['OrderQueryReturnWarnings'] = OrderQueryReturnWarnings
from sdnclient.model.metadata_query_return import MetadataQueryReturn


class TestMetadataQueryReturn(unittest.TestCase):
    """MetadataQueryReturn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataQueryReturn(self):
        """Test MetadataQueryReturn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetadataQueryReturn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
