"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdnclient
from sdnclient.model.order_list_return_orders_inner_order_number import OrderListReturnOrdersInnerOrderNumber


class TestOrderListReturnOrdersInnerOrderNumber(unittest.TestCase):
    """OrderListReturnOrdersInnerOrderNumber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderListReturnOrdersInnerOrderNumber(self):
        """Test OrderListReturnOrdersInnerOrderNumber"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderListReturnOrdersInnerOrderNumber()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
