"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdnclient
from sdnclient.model.order_query_query_fields import OrderQueryQueryFields
globals()['OrderQueryQueryFields'] = OrderQueryQueryFields
from sdnclient.model.order_query import OrderQuery


class TestOrderQuery(unittest.TestCase):
    """OrderQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderQuery(self):
        """Test OrderQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
