"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import cdi_sdn_py
from cdi_sdn_py.model.order_query_query_fields import OrderQueryQueryFields
globals()['OrderQueryQueryFields'] = OrderQueryQueryFields
from cdi_sdn_py.model.metadata_query import MetadataQuery


class TestMetadataQuery(unittest.TestCase):
    """MetadataQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataQuery(self):
        """Test MetadataQuery"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetadataQuery()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
