"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import sdn-client
from sdn-client.model.metadata_query_return_you_search_for_translation_inner_query_field1 import MetadataQueryReturnYouSearchForTranslationInnerQueryField1


class TestMetadataQueryReturnYouSearchForTranslationInnerQueryField1(unittest.TestCase):
    """MetadataQueryReturnYouSearchForTranslationInnerQueryField1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataQueryReturnYouSearchForTranslationInnerQueryField1(self):
        """Test MetadataQueryReturnYouSearchForTranslationInnerQueryField1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MetadataQueryReturnYouSearchForTranslationInnerQueryField1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
