"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "sdn-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="SeadataNet API",
    author="Administrator at Maris",
    author_email="info@maris.nl",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "SeadataNet API"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    A detailed description of the operation.  # noqa: E501
    """
)
