# flake8: noqa

"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from cdi_sdn_py.api_client import ApiClient

# import Configuration
from cdi_sdn_py.configuration import Configuration

# import exceptions
from cdi_sdn_py.exceptions import OpenApiException
from cdi_sdn_py.exceptions import ApiAttributeError
from cdi_sdn_py.exceptions import ApiTypeError
from cdi_sdn_py.exceptions import ApiValueError
from cdi_sdn_py.exceptions import ApiKeyError
from cdi_sdn_py.exceptions import ApiException
