# flake8: noqa

"""
    SeadataNet API

    A detailed description of the operation.  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Contact: info@maris.nl
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from sdn-client.api_client import ApiClient

# import Configuration
from sdn-client.configuration import Configuration

# import exceptions
from sdn-client.exceptions import OpenApiException
from sdn-client.exceptions import ApiAttributeError
from sdn-client.exceptions import ApiTypeError
from sdn-client.exceptions import ApiValueError
from sdn-client.exceptions import ApiKeyError
from sdn-client.exceptions import ApiException
